service: hacker-news-pipeline

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  stage: dev
  # We route all traffic directly to LocalStack endpoints
  endpointDiscovery:
    enabled: false

functions:
  hackerNewsIngest:
    handler: lambdas/hackerNewsIngest.lambda_handler
    events:
      - schedule: rate(24 hours)